# Generated by Django 4.1.2 on 2022-10-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adevactes',
            name='company',
            field=models.CharField(choices=[('test1', 'test2')], default='', max_length=140),
        ),
    ]
