# Generated by Django 4.1.2 on 2022-10-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_details', '0002_adevactes_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adevactes',
            name='company',
            field=models.CharField(choices=[('test1', 'test2')], default='select', max_length=140),
        ),
    ]
