# Generated by Django 4.1.2 on 2022-10-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_details', '0003_alter_adevactes_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adevactes',
            name='company',
            field=models.CharField(choices=[('test1', 'test3')], default='select', max_length=140),
        ),
    ]
