# Generated by Django 4.1.2 on 2022-10-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adv_details', '0004_alter_adevactes_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adevactes',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv_details.company'),
        ),
    ]
