# Generated by Django 4.1.2 on 2022-10-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_details', '0005_alter_adevactes_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='herf',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
